version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev # บอกให้ใช้ไฟล์ Dev ที่เราเพิ่งสร้าง
    ports:
      - "3000:3000"
    volumes:
      - .:/app   # 🟢 หัวใจสำคัญ! ผูกโฟลเดอร์ปัจจุบัน (./) เข้ากับ /app ใน Container
    env_file:
      - .env      # 🟢 โหลดไฟล์ .env ให้โดยอัตโนมัติ หมดปัญหาค่าว่าง!